Refactor AutoCloudConsumer
kushaldas/autocloud pull request #49
Opened 2016-10-05 14:06 UTC by yahzaa

2016-10-17 14:10 UTC, sayanchowdhury requested changes

2016-10-17 14:10 UTC, sayanchowdhury commented on autocloud/consumer.py
> +        else:
We can just remove the `else` block here and set compose_images_json to None in the beginning

2016-10-17 14:10 UTC, sayanchowdhury commented on autocloud/consumer.py
> +                compose_date = datetime.strptime(compose_details['date'], '%Y%m%d')
Will this not break PEP8?

2016-10-17 14:10 UTC, sayanchowdhury commented on autocloud/consumer.py
> +        if compose_images_json:
`NoneType` test should be done as `compose_images_json is not None`

2016-10-18 17:58 UTC, yahzaa commented on autocloud/consumer.py
> +                compose_date = datetime.strptime(compose_details['date'], '%Y%m%d')
no, it's less than 80 cols.

2016-10-18 18:02 UTC, yahzaa commented
updated commit

2016-10-25 10:05 UTC, sayanchowdhury approved these changes

2016-10-25 10:05 UTC, merged